<%@ Page Language="VB" AutoEventWireup="false" MaintainScrollPositionOnPostback="true" CodeFile="MaintainScrollPosition.aspx.vb" Inherits="MaintainScrollPosition" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
    <title>MaintainScrollPositionOnPostBack</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
      <h3>MaintainScrollPositionOnPostBack</h3>    
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br /><br />
      <asp:Button ID="Button1" runat="server" Text="Click Me!" /><br /><br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
      This is some content to scroll...<br />
    </div>
    </form>
</body>
</html>
